//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIBnpWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fooEntities : DbContext
    {
        public fooEntities()
            : base("name=fooEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<kredi_analytics> kredi_analytics { get; set; }
        public DbSet<ses_analytics> ses_analytics { get; set; }
        public DbSet<sigorta_analytics> sigorta_analytics { get; set; }
        public DbSet<video_analytics> video_analytics { get; set; }
    }
}
