//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIBnpWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sigorta_analytics
    {
        public string tc { get; set; }
        public string soru { get; set; }
        public string cevap { get; set; }
        public string time { get; set; }
        public string flag { get; set; }
        public int id { get; set; }
    }
}
